apiVersion: v1
kind: Secret
metadata:
  name: quay-push-secret
data:
  .dockerconfigjson: paste the encoded cfg from your quay.io account here
type: kubernetes.io/dockerconfigjson

# then link this secret to the default pipeline ServiceAccount
# > oc secrets link pipeline quay-push-secret --for=pull,mount