apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitops-dev-pipeline
spec:
  params:
    - default: 'https://github.com/rafaeltuelho/devspaces-quarkus-crud-demo.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision (branch) to be used
      name: git-revision
      type: string
    - name: config-git-url
      type: string
      description: URL of the Git config repository
      default: 'https://github.com/rafaeltuelho/devspaces-quarkus-crud-demo-manifests.git'
    - name: config-dir
      type: string
      description: Configuration directory within the config-git-url with the files
      default: 'config/overlays/dev'
    - name: context-dir
      default: "."
      type: string
      description: Where (sub-dir) to checkout the source relative to the workspace
    - name: image-name
      type: string
      description: the name of the target image including registry
      default: quay.io/rafaeltuelho/devspaces-quarkus-crud-demo
    # no need to pass registry creds using params if you have a proper SA and dockerconfig Secret 
    #  setup to be used in your PipelineRuns (serviceAccount)
    # - name: image-username
    #   type: string
    #   description: the username you use to access the registry
    # - name: image-password
    #   type: string
    #   description: The password you use to access the registry
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.context-dir)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: maven-package
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - clean
            - package
            - '-DskipTests'
            - '-Dquarkus.container-image.build=false' 
            - '-Dquarkus.container-image.builder=jib'
            - '-e'
            - '-B'
            - '-Dmaven.repo.local=$(workspaces.source.path)/.m2'
        - name: CONTEXT_DIR
          value: $(params.context-dir)
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-and-push-image
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - clean
            - package
            - '-DskipTests'
            - '-Dquarkus.container-image.build=true'
            - '-Dquarkus.container-image.push=true'
            - '-Dquarkus.container-image.builder=jib'
            - '-Dquarkus.container-image.image=$(params.image-name)'
            - '-e'
            - '-B'
            - '-Dmaven.repo.local=$(workspaces.source.path)/.m2'
        - name: CONTEXT_DIR
          value: $(params.context-dir)
      runAfter:
        - maven-package
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: extract-image-digest
      params:
        - name: image-digest-path
          value: $(params.context-dir)/target
      runAfter:
        - build-and-push-image
      taskRef:
        kind: Task
        name: extract-image-digest
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: git-update-manifests
      params:
        - name: GIT_REPOSITORY
          value: $(params.config-git-url)
        - name: CURRENT_IMAGE
          value: $(params.image-name):latest
        - name: NEW_IMAGE
          value: $(params.image-name)
        - name: NEW_DIGEST
          value: $(tasks.extract-image-digest.results.DIGEST)
        - name: KUSTOMIZATION_PATH
          value: $(params.config-dir)
      runAfter:
        - extract-image-digest
      taskRef:
        kind: Task
        name: git-update-manifests
      workspaces:
        - name: workspace
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: false
    - name: maven-settings
      optional: false
